# Generated by Django 3.1.7 on 2021-04-15 16:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('buss', '0005_auto_20210415_2126'),
    ]

    operations = [
        migrations.RenameField(
            model_name='passenger',
            old_name='auto_increment_id',
            new_name='id',
        ),
    ]
